# Generated by Django 3.1.2 on 2020-11-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_time_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['project', 'createdDate']},
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://i.pravatar.cc/32'),
        ),
    ]
