# Generated by Django 3.1.2 on 2020-10-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201027_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskCompletedDate',
            field=models.DateField(null=True),
        ),
    ]
