# Generated by Django 3.1.2 on 2020-10-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201029_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='duration',
            field=models.DurationField(default=1),
            preserve_default=False,
        ),
    ]
