# Generated by Django 3.1.2 on 2020-10-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201027_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskCompletedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
