# Generated by Django 3.1.2 on 2020-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default='add an project image', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='add an project image', max_length=250),
        ),
    ]
