# Generated by Django 3.1.2 on 2020-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201102_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://semantic-ui.com/images/avatar/large/steve.jpg', max_length=250),
        ),
    ]
